[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tower_defense"
version = "0.1.0"
description = "A simple Python tower defense game"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name = "Robert Seifert", email = "reobert.rob.seifert@gmail.com" }
]
dependencies = [
    "setuptools<81",
    "pygame>=2.6.1",
    "platformdirs>=4.3.8",
    "tomli-w>=1.2.0",
    "setuptools<81"
]

[project.optional-dependencies]
dev = [
    "invoke>=2.1.0",
    "pyinstaller",
    "build",
    "twine",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"tower_defense" = ["resources/**/*"]

[project.scripts]
tower_defense = "tower_defense.app:main"
