[player]
start_gold = 50

[wave]
period_ms = 1000
shopping_time_s = 5

[level1]
waves = ["GG", "GGGG", "GGGGGGGG"]
map = "terrain.txt"
gold = 30
towers = ["S"]

[level2]
waves = ["GGGG", "GGGGGGGG"]
map = "terrain2.txt"
gold = 50
towers = ["SM"]

[level3]
waves = ["OOO",  "OOOO", "OOOOOOOO"]
map = "terrain3.txt"
gold = 30
towers = ["SM"]

[level4]
waves = ["OOO", "OOGO", "GOOGO"]
map = "terrain4.txt"
gold = 30
towers = ["SM"]

[level5]
waves = ["OGOGOG",  "OOOGOO", "GGGOGGG"]
map = "terrain5.txt"
gold = 30
towers = ["SM"]

[level6]
waves = ["SSS",  "SGSSS", "OSSS"]
map = "terrain6.txt"
gold = 30
towers = ["SM"]

[level7]
waves = ["SGOOGSS",  "SSOGOSS", "G"]
map = "terrain7.txt"
gold = 30
towers = ["SM"]

[level8]
waves = ["OOOGGSSSSG",  "GOOOOOSSSSOO"]
map = "terrain8.txt"
gold = 30
towers = ["SM"]

[level9]
waves = ["",  ""]
map = "terrain9.txt"
gold = 30
towers = ["SM"]

[level10]
waves = ["",  ""]
map = "terrain10.txt"
gold = 30
towers = ["SM"]

[level11]
waves = ["",  ""]
map = "terrain11.txt"
gold = 30
towers = ["SM"]

[level12]
waves = ["",  ""]
map = "terrain12.txt"
gold = 30
towers = ["SM"]

[level13]
waves = ["",  ""]
map = "terrain13.txt"
towers = ["SM"]

[level14]
waves = ["",  ""]
map = "terrain14.txt"
towers = ["SM"]

[towers]
[towers.stone]
damage = 10
attack_speed_ms = 50
range = 5
price = 30
after_wave = 0

[towers.meteor]
damage = 5
attack_speed_ms = 15
range = 3
price = 50
after_wave = 3

[towers.fire]
damage = 20
attack_speed_ms = 0
range = 3
price = 5
after_wave = 5

[monsters]
[monsters.goblin]
speed = 1.5
damage = 10
attack_speed = 80
health = 30
value = 10

[monsters.orc]
speed = 1
damage = 15
attack_speed = 100
health = 50
value = 20

[monsters.spider]
speed = 2.5
damage = 10
attack_speed = 50
health = 20
value = 15

[castle]
health = 100
